---
title: "question 2"
author: "xinyi Lin"
date: "2/28/2019"
output:
  pdf_document: default
  html_document: default
---

```{r}
library(tidyverse)
library(matrixcalc)
```

```{r}
cancer_data = read_csv("./breast-cancer-1.csv")
```

## classical Newton Raphson

```{r}
logisticstuff <- function(x, y, betavec) {
  u <- x %*% betavec
  expu <- exp(u)
  loglik = vector(mode = "numeric", 569)
  for(i in 1:569)
    loglik[i] = y[i]*u[i] - log(1 + expu[i])
  loglik_value = sum(loglik)
  # Log-likelihood at betavec
  p <- expu / (1 + expu)
  # P(Y_i=1|x_i)
  grad = vector(mode = "numeric", 13)
  #grad[1] = sum(y - p)
  for(i in 1:13)
    grad[i] = sum(t(x[,i])%*%(y - p))
  #Hess <- -t(x)%*%p%*%t(1-p)%*%x
  Hess = hess_cal(x, p)
  return(list(loglik = loglik_value, grad = grad, Hess = Hess))
}
```

```{r}
hess_cal = function(x,p){
  len = length(p)
  hess = matrix(0, ncol(x), ncol(x))
  for (i in 1:len) {
    x_t = t(x[i,])
    unit = t(x_t)%*%x_t*p[i]*(1-p[i])
    #unit = t(x[i,])%*%x[i,]*p[i]*(1-p[i])
    hess = hess + unit
  }
  return(-hess)
}
```

Newton-Raphson process

```{r}
NewtonRaphson <- function(x, y, logisticstuff, start, tol=1e-10, maxiter = 200) {
  i <- 0
  cur <- start
  stuff <- logisticstuff(x, y, cur)
  res = c(0, cur)
  #res <- c(0, stuff$loglik, cur)
  prevloglik <- -Inf      # To make sure it iterates
  #while(i < maxiter && abs(stuff$loglik - prevloglik) > tol && stuff$loglik > -Inf)
  while(i < maxiter && abs(stuff$loglik - prevloglik) > tol)
 {
    i <- i + 1
    prevloglik <- stuff$loglik
    prev <- cur
    cur <- prev - solve(stuff$Hess) %*% stuff$grad
    stuff <- logisticstuff(x, y, cur)        # log-lik, gradient, Hessian
    res = rbind(res, c(i, cur))
    #res <- rbind(res, c(i, stuff$loglik, cur))
    # Add current values to results matrix
}
  return(res)
}
```

Using data to get answer

Variables we used: mean radius, mean texture, mean perimeter, mean smoothness,mean compactness, mean concavity, mean concave points, mean fractal dimension, mean symmetry, standard error of radius, perimeter, and symmetry. 

```{r}
intercept = rep(1, 569)
central = function(x){
  x = (x-mean(x))/sd(x)
  return(x)
}
x = cancer_data %>% 
  dplyr::select(radius_mean:fractal_dimension_mean, radius_se, perimeter_worst, symmetry_worst) %>% 
  dplyr::select(-area_mean) %>% 
  apply(2, central) %>% 
  cbind(intercept, .) %>% 
  as.matrix()
#colnames(x) = NULL
y = as.vector(ifelse(cancer_data$diagnosis=="M",1,0))  # response variables
beta = rep(0.001,13)
ans1 = NewtonRaphson(x, y, logisticstuff, beta)
ans1
```

```{r}
glm_x = x[,2:13]
cancer_model <- glm(y ~ glm_x, family = binomial(link = "logit"))
summary(cancer_model)
```

## modified Hessian

```{r}
modified <- function(x, y, logisticstuff, start, tol=1e-5, maxiter = 200){ 
  i <- 0 
  cur <- start 
  beta_len <- length(start)
  stuff <- logisticstuff(x, y, cur) 
  res = c(0, cur)
  #res <- c(0, stuff$loglik,cur)
  prevloglik <- -Inf # To make sure it iterates 
  while(i <= maxiter && abs(stuff$loglik - prevloglik) > tol)
  #while(i <= maxiter && abs(stuff$loglik - prevloglik) > tol && stuff$loglik > -Inf) 
    { i <- i + 1 
    prevloglik <- stuff$loglik 
    prev <- cur 
    lambda = 0
    while (is.negative.definite(stuff$Hess-lambda*diag(beta_len)) == FALSE) {
      lambda = lambda + 1
    }
    cur <- prev - solve(stuff$Hess-lambda*diag(beta_len)) %*% stuff$grad
    #cur <- prev + (diag(beta_len)/10)%*%(stuff$grad)
    #cur = prev + t(stuff$grad)%*%(stuff$grad)
    stuff <- logisticstuff(x, y, cur) # log-lik, gradient, Hessian
    res = rbind(res, c(i, cur))
    #res <- rbind(res, c(i, stuff$loglik, cur))
    }  
  return(round(res,2))
}
#ans2 <- modified(x, y, logisticstuff, beta, maxiter = 1000)
#ans2
<<<<<<< HEAD
```
=======
```




>>>>>>> 59599854c459b775a6b6a48442d16c86a181505c
